Repository UN-OCHA/hpc-cdm, pull requests merged in 2021-11, with the labels that each got.

#235 Update React to v17
  package-lock.json
  package.json
Labels: ready for review

#236 :package: Prepare release v1.1.4 and deploy to stage
  apps/hpc-cdm/src/environments/config-loader.ts
  apps/hpc-cdm/src/environments/environment.prod.ts
  package-lock.json
  package.json
Labels: deployment

#237 Update develop with changes from env/stage
  package-lock.json
  package.json
Labels: mergeback

#238 🚀 Release `v1.1.4` and deploy to production
  apps/hpc-cdm/src/environments/config-loader.ts
  apps/hpc-cdm/src/environments/environment.prod.ts
  package-lock.json
  package.json
Labels: deployment
