Repository UN-OCHA/hpc-cdm, pull requests merged in 2021-12, with the labels that each got.

#243 ✨ HPC-8318: Allow for CDM frontend to handle multiple reporting windows
  apps/hpc-cdm/src/app/components/enketo/formToolbar/StatusChangeButtons.tsx
  apps/hpc-cdm/src/app/components/enketo/formToolbar/index.tsx
  apps/hpc-cdm/src/app/components/enketo/formToolbar/indicator.tsx
  apps/hpc-cdm/src/app/components/enketo/index.tsx
  apps/hpc-cdm/src/app/components/operation-cluster-form-assignments-list.tsx
  apps/hpc-cdm/src/app/components/operation-form-assignments-list.tsx
  apps/hpc-cdm/src/app/components/target-access-management.tsx
  apps/hpc-cdm/src/app/pages/operation-cluster-form-assignments.tsx
  apps/hpc-cdm/src/app/pages/operation-cluster-forms.tsx
  apps/hpc-cdm/src/app/pages/operation-form-assignments.tsx
  apps/hpc-cdm/src/app/pages/operation-forms.tsx
  apps/hpc-cdm/src/app/utils/reportingWindows.ts
  apps/hpc-cdm/src/i18n/langs/en.json
  apps/hpc-cdm/src/i18n/langs/fr.json
  libs/hpc-data/src/lib/reporting-windows.ts
  libs/hpc-dummy/src/lib/data-types.ts
  libs/hpc-dummy/src/lib/data.ts
  libs/hpc-dummy/src/lib/dummy.ts
  libs/hpc-ui/src/index.ts
  libs/hpc-ui/src/lib/components/list-item.tsx
  libs/hpc-ui/src/lib/components/list.tsx
  libs/hpc-ui/src/lib/components/sidebar-navigation.tsx
  libs/hpc-ui/src/lib/theme.tsx
  package-lock.json
  package.json
Labels: ready for review, deploy to red.dev

#242 ⬆️ HPC-8322: Update @material-ui/core
  package-lock.json
  package.json
Labels: ready for review

#244 🐛 HPC-8330: Remove incorrect status component
  apps/hpc-cdm/src/app/components/enketo/formToolbar/indicator.tsx
Labels: ready for review, deploy to red.dev

#245 📦️ Prepare release `v1.2.0` and deploy to stage
  apps/hpc-cdm/src/app/components/enketo/formToolbar/StatusChangeButtons.tsx
  apps/hpc-cdm/src/app/components/enketo/formToolbar/index.tsx
  apps/hpc-cdm/src/app/components/enketo/formToolbar/indicator.tsx
  apps/hpc-cdm/src/app/components/enketo/index.tsx
  apps/hpc-cdm/src/app/components/operation-cluster-form-assignments-list.tsx
  apps/hpc-cdm/src/app/components/operation-form-assignments-list.tsx
  apps/hpc-cdm/src/app/components/target-access-management.tsx
  apps/hpc-cdm/src/app/pages/operation-cluster-form-assignments.tsx
  apps/hpc-cdm/src/app/pages/operation-cluster-forms.tsx
  apps/hpc-cdm/src/app/pages/operation-form-assignments.tsx
  apps/hpc-cdm/src/app/pages/operation-forms.tsx
  apps/hpc-cdm/src/app/utils/reportingWindows.ts
  apps/hpc-cdm/src/i18n/langs/en.json
  apps/hpc-cdm/src/i18n/langs/fr.json
  libs/hpc-data/src/lib/reporting-windows.ts
  libs/hpc-dummy/src/lib/data-types.ts
  libs/hpc-dummy/src/lib/data.ts
  libs/hpc-dummy/src/lib/dummy.ts
  libs/hpc-ui/src/index.ts
  libs/hpc-ui/src/lib/components/list-item.tsx
  libs/hpc-ui/src/lib/components/list.tsx
  libs/hpc-ui/src/lib/components/sidebar-navigation.tsx
  libs/hpc-ui/src/lib/theme.tsx
  package-lock.json
  package.json
Labels: deployment

#246 Update develop with changes from env/stage
  package-lock.json
  package.json
Labels: mergeback

#247 🚀 Release `v1.2.0` and deploy to production
  apps/hpc-cdm/src/app/components/enketo/formToolbar/StatusChangeButtons.tsx
  apps/hpc-cdm/src/app/components/enketo/formToolbar/index.tsx
  apps/hpc-cdm/src/app/components/enketo/formToolbar/indicator.tsx
  apps/hpc-cdm/src/app/components/enketo/index.tsx
  apps/hpc-cdm/src/app/components/operation-cluster-form-assignments-list.tsx
  apps/hpc-cdm/src/app/components/operation-form-assignments-list.tsx
  apps/hpc-cdm/src/app/components/target-access-management.tsx
  apps/hpc-cdm/src/app/pages/operation-cluster-form-assignments.tsx
  apps/hpc-cdm/src/app/pages/operation-cluster-forms.tsx
  apps/hpc-cdm/src/app/pages/operation-form-assignments.tsx
  apps/hpc-cdm/src/app/pages/operation-forms.tsx
  apps/hpc-cdm/src/app/utils/reportingWindows.ts
  apps/hpc-cdm/src/i18n/langs/en.json
  apps/hpc-cdm/src/i18n/langs/fr.json
  libs/hpc-data/src/lib/reporting-windows.ts
  libs/hpc-dummy/src/lib/data-types.ts
  libs/hpc-dummy/src/lib/data.ts
  libs/hpc-dummy/src/lib/dummy.ts
  libs/hpc-ui/src/index.ts
  libs/hpc-ui/src/lib/components/list-item.tsx
  libs/hpc-ui/src/lib/components/list.tsx
  libs/hpc-ui/src/lib/components/sidebar-navigation.tsx
  libs/hpc-ui/src/lib/theme.tsx
  package-lock.json
  package.json
Labels: deployment

#250 Hotfix: Changes required for HPC-8317
  apps/hpc-cdm/src/app/components/enketo/formToolbar/assignUsersButton.tsx
  apps/hpc-cdm/src/app/components/operation-form-assignments-list.tsx
  apps/hpc-cdm/src/app/utils/reportingWindows.ts
  apps/hpc-cdm/src/i18n/langs/en.json
  apps/hpc-cdm/src/i18n/langs/fr.json
  libs/hpc-ui/src/lib/util.ts
  package-lock.json
  package.json
Labels: ready for review

#251 Update develop with changes from env/stage
  apps/hpc-cdm/src/app/components/enketo/formToolbar/assignUsersButton.tsx
  apps/hpc-cdm/src/app/components/operation-form-assignments-list.tsx
  apps/hpc-cdm/src/app/utils/reportingWindows.ts
  apps/hpc-cdm/src/i18n/langs/en.json
  apps/hpc-cdm/src/i18n/langs/fr.json
  libs/hpc-ui/src/lib/util.ts
  package-lock.json
  package.json
Labels: mergeback

#252 🚀 Release v1.2.0-hotfix-1 and deploy to production
  apps/hpc-cdm/src/app/components/enketo/formToolbar/assignUsersButton.tsx
  apps/hpc-cdm/src/app/components/operation-form-assignments-list.tsx
  apps/hpc-cdm/src/app/utils/reportingWindows.ts
  apps/hpc-cdm/src/i18n/langs/en.json
  apps/hpc-cdm/src/i18n/langs/fr.json
  libs/hpc-ui/src/lib/util.ts
  package-lock.json
  package.json
Labels: deployment
