Repository UN-OCHA/hpc-cdm, pull requests merged in 2022-07, with the labels that each got.

#307 Fix automated tests
  apps/hpc-cdm-e2e/cypress.json
  apps/hpc-cdm-e2e/src/integration/app.spec.ts
  apps/hpc-cdm-e2e/src/plugins/index.js
  apps/hpc-cdm-e2e/src/support/app.po.ts
  apps/hpc-cdm-e2e/src/support/commands.ts
  apps/hpc-cdm/src/app/app.spec.tsx
  libs/hpc-dummy/src/index.ts
  libs/hpc-dummy/src/lib/dummy.ts
  libs/hpc-ui/src/lib/components/header.spec.tsx
Labels: ready for review

#316 Update MUI from v4 to v5
  apps/hpc-cdm/src/app/components/enketo/formToolbar/indicator.tsx
  apps/hpc-cdm/src/app/components/enketo/modals/assignedUsersModal.tsx
  apps/hpc-cdm/src/app/components/enketo/modals/validationOnNavigationModal.tsx
  apps/hpc-cdm/src/app/components/enketo/modals/validationOnSubmitModal.tsx
  apps/hpc-cdm/src/app/components/enketo/submit-button.tsx
  apps/hpc-cdm/src/app/components/form-assignments-list.tsx
  apps/hpc-cdm/src/app/components/target-access-management-add-user.tsx
  apps/hpc-cdm/webpack.js
  libs/hpc-dummy/src/lib/users.tsx
  libs/hpc-ui/src/lib/components/actionable-button.tsx
  libs/hpc-ui/src/lib/components/actionable-dropdown.tsx
  libs/hpc-ui/src/lib/components/dialogs.tsx
  libs/hpc-ui/src/lib/components/header.tsx
  libs/hpc-ui/src/lib/components/language-picker.tsx
  libs/hpc-ui/src/lib/components/loader.tsx
  libs/hpc-ui/src/lib/theme.tsx
  package-lock.json
  package.json
  tsconfig.base.json
Labels: ready for merge

#317 📦️ Prepare release `v1.3.7` and deploy to stage
  apps/hpc-cdm-e2e/cypress.json
  apps/hpc-cdm-e2e/src/integration/app.spec.ts
  apps/hpc-cdm-e2e/src/plugins/index.js
  apps/hpc-cdm-e2e/src/support/app.po.ts
  apps/hpc-cdm-e2e/src/support/commands.ts
  apps/hpc-cdm/src/app/app.spec.tsx
  apps/hpc-cdm/src/app/components/enketo/formToolbar/indicator.tsx
  apps/hpc-cdm/src/app/components/enketo/modals/assignedUsersModal.tsx
  apps/hpc-cdm/src/app/components/enketo/modals/validationOnNavigationModal.tsx
  apps/hpc-cdm/src/app/components/enketo/modals/validationOnSubmitModal.tsx
  apps/hpc-cdm/src/app/components/enketo/submit-button.tsx
  apps/hpc-cdm/src/app/components/form-assignments-list.tsx
  apps/hpc-cdm/src/app/components/target-access-management-add-user.tsx
  apps/hpc-cdm/webpack.js
  libs/hpc-dummy/src/index.ts
  libs/hpc-dummy/src/lib/dummy.ts
  libs/hpc-dummy/src/lib/users.tsx
  libs/hpc-ui/src/lib/components/actionable-button.tsx
  libs/hpc-ui/src/lib/components/actionable-dropdown.tsx
  libs/hpc-ui/src/lib/components/dialogs.tsx
  libs/hpc-ui/src/lib/components/header.spec.tsx
  libs/hpc-ui/src/lib/components/header.tsx
  libs/hpc-ui/src/lib/components/language-picker.tsx
  libs/hpc-ui/src/lib/components/loader.tsx
  libs/hpc-ui/src/lib/theme.tsx
  package-lock.json
  package.json
  tsconfig.base.json
Labels: deployment

#318 Update develop with changes from env/stage
  package-lock.json
  package.json
Labels: mergeback

#305 HPC-8242 - FTS Admin setup
  README.md
  apps/hpc-ftsadmin-e2e/.eslintrc.json
  apps/hpc-ftsadmin-e2e/cypress.json
  apps/hpc-ftsadmin-e2e/src/fixtures/example.json
  apps/hpc-ftsadmin-e2e/src/integration/app.spec.ts
  apps/hpc-ftsadmin-e2e/src/support/commands.ts
  apps/hpc-ftsadmin-e2e/src/support/index.ts
  apps/hpc-ftsadmin-e2e/tsconfig.e2e.json
  apps/hpc-ftsadmin-e2e/tsconfig.json
  apps/hpc-ftsadmin/.babelrc
  apps/hpc-ftsadmin/.browserslistrc
  apps/hpc-ftsadmin/.eslintrc.json
  apps/hpc-ftsadmin/babel-jest.config.json
  apps/hpc-ftsadmin/jest.config.js
  apps/hpc-ftsadmin/src/app/app.spec.tsx
  apps/hpc-ftsadmin/src/app/app.tsx
  apps/hpc-ftsadmin/src/app/components/page-meta.tsx
  apps/hpc-ftsadmin/src/app/context.ts
  apps/hpc-ftsadmin/src/app/layout.ts
  apps/hpc-ftsadmin/src/app/pages/flows-list.tsx
  apps/hpc-ftsadmin/src/app/pages/not-found.tsx
  apps/hpc-ftsadmin/src/app/pages/not-logged-in.tsx
  apps/hpc-ftsadmin/src/app/paths.ts
  apps/hpc-ftsadmin/src/assets/.gitkeep
  apps/hpc-ftsadmin/src/environments/config-loader.ts
  apps/hpc-ftsadmin/src/environments/env.json
  apps/hpc-ftsadmin/src/environments/environment.dev-live.ts
  apps/hpc-ftsadmin/src/environments/environment.prod.ts
  apps/hpc-ftsadmin/src/environments/environment.ts
  apps/hpc-ftsadmin/src/environments/interface.ts
  apps/hpc-ftsadmin/src/favicon.ico
  apps/hpc-ftsadmin/src/i18n/iface.ts
  apps/hpc-ftsadmin/src/i18n/index.ts
  apps/hpc-ftsadmin/src/i18n/langs/ar.json
  apps/hpc-ftsadmin/src/i18n/langs/ar.ts
  apps/hpc-ftsadmin/src/i18n/langs/en.json
  apps/hpc-ftsadmin/src/i18n/langs/en.ts
  apps/hpc-ftsadmin/src/i18n/langs/fr.json
  apps/hpc-ftsadmin/src/i18n/langs/fr.ts
  apps/hpc-ftsadmin/src/index.html
  apps/hpc-ftsadmin/src/main.tsx
  apps/hpc-ftsadmin/src/polyfills.ts
  apps/hpc-ftsadmin/tsconfig.app.json
  apps/hpc-ftsadmin/tsconfig.json
  apps/hpc-ftsadmin/tsconfig.spec.json
  apps/hpc-ftsadmin/webpack.js
  libs/hpc-dummy/src/lib/dummy.ts
  libs/hpc-ui/src/lib/components/main-navigation.tsx
  libs/hpc-ui/src/lib/styling.tsx
  libs/hpc-ui/src/lib/theme.tsx
  workspace.json
Labels: ready for review

#319 🚀 Release `v1.3.7` and deploy to production
  apps/hpc-cdm-e2e/cypress.json
  apps/hpc-cdm-e2e/src/integration/app.spec.ts
  apps/hpc-cdm-e2e/src/plugins/index.js
  apps/hpc-cdm-e2e/src/support/app.po.ts
  apps/hpc-cdm-e2e/src/support/commands.ts
  apps/hpc-cdm/src/app/app.spec.tsx
  apps/hpc-cdm/src/app/components/enketo/formToolbar/indicator.tsx
  apps/hpc-cdm/src/app/components/enketo/modals/assignedUsersModal.tsx
  apps/hpc-cdm/src/app/components/enketo/modals/validationOnNavigationModal.tsx
  apps/hpc-cdm/src/app/components/enketo/modals/validationOnSubmitModal.tsx
  apps/hpc-cdm/src/app/components/enketo/submit-button.tsx
  apps/hpc-cdm/src/app/components/form-assignments-list.tsx
  apps/hpc-cdm/src/app/components/target-access-management-add-user.tsx
  apps/hpc-cdm/webpack.js
  libs/hpc-dummy/src/index.ts
  libs/hpc-dummy/src/lib/dummy.ts
  libs/hpc-dummy/src/lib/users.tsx
  libs/hpc-ui/src/lib/components/actionable-button.tsx
  libs/hpc-ui/src/lib/components/actionable-dropdown.tsx
  libs/hpc-ui/src/lib/components/dialogs.tsx
  libs/hpc-ui/src/lib/components/header.spec.tsx
  libs/hpc-ui/src/lib/components/header.tsx
  libs/hpc-ui/src/lib/components/language-picker.tsx
  libs/hpc-ui/src/lib/components/loader.tsx
  libs/hpc-ui/src/lib/theme.tsx
  package-lock.json
  package.json
  tsconfig.base.json
Labels: deployment
