Repository UN-OCHA/hpc-cdm, pull requests merged in 2022-12, with the labels that each got.

#335 HPC:8794 Fix disappeared HPC logo
  libs/hpc-ui/src/lib/components/main-navigation.tsx
Labels: ready for merge

#336 📦️ Prepare release `v1.3.8` and deploy to stage
  .env.example.json
  .github/workflows/codeql-analysis.yml
  .github/workflows/workflow.yml
  apps/hpc-ftsadmin/src/app/app.tsx
  apps/hpc-ftsadmin/src/environments/config-loader.ts
  apps/hpc-ftsadmin/src/environments/interface.ts
  apps/hpc-ftsadmin/src/i18n/langs/en.json
  apps/hpc-ftsadmin/src/i18n/langs/fr.json
  libs/hpc-core/src/lib/config/index.ts
  libs/hpc-ui/src/lib/components/main-navigation.tsx
  package-lock.json
  package.json
Labels: deployment

#337 Update develop with changes from env/stage
  package-lock.json
  package.json
Labels: mergeback

#338 📦️ HPC-8794: [Hotfix] Fix disappeared HPC logo separator
  apps/hpc-cdm/src/app/app.tsx
  libs/hpc-ui/src/lib/components/main-navigation.tsx
  package-lock.json
  package.json
Labels: ready for review

#339 Update develop with changes from env/stage
  apps/hpc-cdm/src/app/app.tsx
  libs/hpc-ui/src/lib/components/main-navigation.tsx
  package-lock.json
  package.json
Labels: mergeback

#340 🚀 Release `v1.3.9-hotfix-1` and deploy to production
  .env.example.json
  .github/workflows/codeql-analysis.yml
  .github/workflows/workflow.yml
  apps/hpc-cdm/src/app/app.tsx
  apps/hpc-ftsadmin/src/app/app.tsx
  apps/hpc-ftsadmin/src/environments/config-loader.ts
  apps/hpc-ftsadmin/src/environments/interface.ts
  apps/hpc-ftsadmin/src/i18n/langs/en.json
  apps/hpc-ftsadmin/src/i18n/langs/fr.json
  libs/hpc-core/src/lib/config/index.ts
  libs/hpc-ui/src/lib/components/main-navigation.tsx
  package-lock.json
  package.json
Labels: deployment
