Repository UN-OCHA/hpc-cdm, pull requests merged in 2022-08, with the labels that each got.

#322 OPS-8532: Use `stable-beagle` as nginx image tag
  Dockerfile
Labels: ready for review

#323 📦️ Prepare release `v1.3.8` and deploy to stage
  Dockerfile
  README.md
  apps/hpc-ftsadmin-e2e/.eslintrc.json
  apps/hpc-ftsadmin-e2e/cypress.json
  apps/hpc-ftsadmin-e2e/src/fixtures/example.json
  apps/hpc-ftsadmin-e2e/src/integration/app.spec.ts
  apps/hpc-ftsadmin-e2e/src/support/commands.ts
  apps/hpc-ftsadmin-e2e/src/support/index.ts
  apps/hpc-ftsadmin-e2e/tsconfig.e2e.json
  apps/hpc-ftsadmin-e2e/tsconfig.json
  apps/hpc-ftsadmin/.babelrc
  apps/hpc-ftsadmin/.browserslistrc
  apps/hpc-ftsadmin/.eslintrc.json
  apps/hpc-ftsadmin/babel-jest.config.json
  apps/hpc-ftsadmin/jest.config.js
  apps/hpc-ftsadmin/src/app/app.spec.tsx
  apps/hpc-ftsadmin/src/app/app.tsx
  apps/hpc-ftsadmin/src/app/components/page-meta.tsx
  apps/hpc-ftsadmin/src/app/context.ts
  apps/hpc-ftsadmin/src/app/layout.ts
  apps/hpc-ftsadmin/src/app/pages/flows-list.tsx
  apps/hpc-ftsadmin/src/app/pages/not-found.tsx
  apps/hpc-ftsadmin/src/app/pages/not-logged-in.tsx
  apps/hpc-ftsadmin/src/app/paths.ts
  apps/hpc-ftsadmin/src/assets/.gitkeep
  apps/hpc-ftsadmin/src/environments/config-loader.ts
  apps/hpc-ftsadmin/src/environments/env.json
  apps/hpc-ftsadmin/src/environments/environment.dev-live.ts
  apps/hpc-ftsadmin/src/environments/environment.prod.ts
  apps/hpc-ftsadmin/src/environments/environment.ts
  apps/hpc-ftsadmin/src/environments/interface.ts
  apps/hpc-ftsadmin/src/favicon.ico
  apps/hpc-ftsadmin/src/i18n/iface.ts
  apps/hpc-ftsadmin/src/i18n/index.ts
  apps/hpc-ftsadmin/src/i18n/langs/ar.json
  apps/hpc-ftsadmin/src/i18n/langs/ar.ts
  apps/hpc-ftsadmin/src/i18n/langs/en.json
  apps/hpc-ftsadmin/src/i18n/langs/en.ts
  apps/hpc-ftsadmin/src/i18n/langs/fr.json
  apps/hpc-ftsadmin/src/i18n/langs/fr.ts
  apps/hpc-ftsadmin/src/index.html
  apps/hpc-ftsadmin/src/main.tsx
  apps/hpc-ftsadmin/src/polyfills.ts
  apps/hpc-ftsadmin/tsconfig.app.json
  apps/hpc-ftsadmin/tsconfig.json
  apps/hpc-ftsadmin/tsconfig.spec.json
  apps/hpc-ftsadmin/webpack.js
  libs/hpc-dummy/src/lib/dummy.ts
  libs/hpc-ui/src/lib/components/main-navigation.tsx
  libs/hpc-ui/src/lib/styling.tsx
  libs/hpc-ui/src/lib/theme.tsx
  package-lock.json
  package.json
  workspace.json
Labels: deployment

#324 Update develop with changes from env/stage
  package-lock.json
  package.json
Labels: mergeback
