Repository UN-OCHA/hpc-cdm, pull requests merged in 2022-01, with the labels that each got.

#255 Introduce `ISO_DATE_FROM_STRING` utility type
  libs/hpc-data/src/lib/util.ts
Labels: ready for review

#256 📦️ Prepare release `v1.2.1` and deploy to stage
  libs/hpc-data/src/lib/util.ts
  package-lock.json
  package.json
Labels: deployment

#257 Update develop with changes from env/stage
  package-lock.json
  package.json
Labels: mergeback

#258 🚀 Release `v1.2.1` and deploy to production
  libs/hpc-data/src/lib/util.ts
  package-lock.json
  package.json
Labels: deployment

#241 HPC-8351: Upgrade Node.js from v12 to v16
  .github/workflows/codeql-analysis.yml
  .github/workflows/label-sync.yml
  .github/workflows/workflow.yml
  .npmrc
  Dockerfile
  package-lock.json
  package.json
Labels: ready for merge
