Repository UN-OCHA/hpc-cdm, pull requests merged in 2023-12, with the labels that each got.

#413 HPC-9088: Update to Compose V2
  README.md
  compose.yaml
Labels: ready for merge

#415 📦️ Prepare release `v1.7.2` and deploy to stage
  README.md
  compose.yaml
  package-lock.json
  package.json
Labels: deployment

#416 Update develop with changes from env/stage
  package-lock.json
  package.json
Labels: mergeback

#417 🚀 Release `v1.7.2` and deploy to production
  README.md
  compose.yaml
  package-lock.json
  package.json
Labels: deployment
