Repository UN-OCHA/hpc-cdm, pull requests merged in 2023-07, with the labels that each got.

#388 HPC-8808: Upgrade to Node v18 and NPM v9
  .github/workflows/codeql-analysis.yml
  .github/workflows/workflow.yml
  Dockerfile
  package-lock.json
  package.json
Labels: ready for merge

#389 Fix warnings occuring during lint
  apps/hpc-cdm/src/app/components/enketo/index.tsx
  nx.json
  package-lock.json
  package.json
Labels: ready for review

#390 📦️ Prepare release `v1.6.0` and deploy to stage
  .github/workflows/codeql-analysis.yml
  .github/workflows/workflow.yml
  Dockerfile
  apps/hpc-cdm/src/app/components/enketo/index.tsx
  nx.json
  package-lock.json
  package.json
Labels: deployment

#392 🚀 Release `v1.6.0` and deploy to production
  .github/workflows/codeql-analysis.yml
  .github/workflows/workflow.yml
  Dockerfile
  apps/hpc-cdm/src/app/components/enketo/index.tsx
  nx.json
  package-lock.json
  package.json
Labels: deployment
