Repository UN-OCHA/hpc-cdm, pull requests merged in 2023-04, with the labels that each got.

#366 HPC-9035: :globe_with_meridians: Don't bundle entire package.json in CDM
  apps/hpc-cdm/src/app/app.tsx
  apps/hpc-cdm/tsconfig.spec.json
  apps/hpc-cdm/webpack.globals.d.ts
  apps/hpc-cdm/webpack.js
Labels: ready for review

#367 HPC-9036 Give unique key prop to list items in CDM
  apps/hpc-cdm/src/app/components/enketo/modals/assignedUsersModal.tsx
  apps/hpc-cdm/src/app/components/target-access-management.tsx
  apps/hpc-cdm/src/app/pages/operation-clusters.tsx
  apps/hpc-cdm/src/app/pages/operations-list.tsx
  libs/hpc-ui/src/lib/components/language-picker.tsx
  libs/hpc-ui/src/lib/components/main-navigation.tsx
Labels: ready for merge

#368 📦️ Prepare release `v1.4.2` and deploy to stage
  apps/hpc-cdm/src/app/app.tsx
  apps/hpc-cdm/src/app/components/enketo/modals/assignedUsersModal.tsx
  apps/hpc-cdm/src/app/components/target-access-management.tsx
  apps/hpc-cdm/src/app/pages/operation-clusters.tsx
  apps/hpc-cdm/src/app/pages/operations-list.tsx
  apps/hpc-cdm/tsconfig.spec.json
  apps/hpc-cdm/webpack.globals.d.ts
  apps/hpc-cdm/webpack.js
  libs/hpc-ui/src/lib/components/language-picker.tsx
  libs/hpc-ui/src/lib/components/main-navigation.tsx
  package-lock.json
  package.json
Labels: deployment

#369 Update develop with changes from env/stage
  package-lock.json
  package.json
Labels: mergeback

#370 🚀 Release `v1.4.2` and deploy to production
  apps/hpc-cdm/src/app/app.tsx
  apps/hpc-cdm/src/app/components/enketo/modals/assignedUsersModal.tsx
  apps/hpc-cdm/src/app/components/target-access-management.tsx
  apps/hpc-cdm/src/app/pages/operation-clusters.tsx
  apps/hpc-cdm/src/app/pages/operations-list.tsx
  apps/hpc-cdm/tsconfig.spec.json
  apps/hpc-cdm/webpack.globals.d.ts
  apps/hpc-cdm/webpack.js
  libs/hpc-ui/src/lib/components/language-picker.tsx
  libs/hpc-ui/src/lib/components/main-navigation.tsx
  package-lock.json
  package.json
Labels: deployment
