Repository UN-OCHA/hpc-cdm, pull requests merged in 2023-11, with the labels that each got.

#401 HPC-9232 & HPC-9238: Upgrade to Node.js v20 and NPM v10
  .github/workflows/codeql-analysis.yml
  .github/workflows/workflow.yml
  .prettierrc
  Dockerfile
  libs/hpc-ui/src/lib/i18n/index.tsx
  package-lock.json
  package.json
Labels: dependencies, ready for merge

#402 📦️ Prepare release `v1.7.0` and deploy to stage
  .github/workflows/codeql-analysis.yml
  .github/workflows/workflow.yml
  .prettierrc
  Dockerfile
  libs/hpc-ui/src/lib/i18n/index.tsx
  package-lock.json
  package.json
Labels: deployment

#403 Update develop with changes from env/stage
  package-lock.json
  package.json
Labels: mergeback

#404 🚀 Release `v1.7.0` and deploy to production
  .github/workflows/codeql-analysis.yml
  .github/workflows/workflow.yml
  .prettierrc
  Dockerfile
  libs/hpc-ui/src/lib/i18n/index.tsx
  package-lock.json
  package.json
Labels: deployment

#408 📦️ Prepare release `v1.7.1` and deploy to stage
  package-lock.json
  package.json
Labels: deployment

#410 🚀 Release `v1.7.1` and deploy to production
  package-lock.json
  package.json
Labels: deployment
