Repository UN-OCHA/hpc-cdm, pull requests merged in 2023-03, with the labels that each got.

#351 🌐 HPC-8998: Add Spanish translation
  apps/hpc-cdm/src/app/components/enketo/index.tsx
  apps/hpc-cdm/src/app/components/form-assignments-list.tsx
  apps/hpc-cdm/src/app/pages/not-logged-in.tsx
  apps/hpc-cdm/src/environments/interface.ts
  apps/hpc-cdm/src/i18n/index.ts
  apps/hpc-cdm/src/i18n/langs/en.json
  apps/hpc-cdm/src/i18n/langs/es.json
  apps/hpc-cdm/src/i18n/langs/es.ts
  apps/hpc-cdm/src/i18n/langs/fr.json
  apps/hpc-cdm/src/libraries/dayjs.ts
  libs/hpc-core/src/lib/i18n/index.ts
  libs/hpc-core/src/lib/session.ts
  libs/hpc-core/src/lib/util/index.ts
  libs/hpc-live/src/lib/live.ts
  libs/hpc-live/src/lib/model.ts
  libs/hpc-ui/src/lib/assets/icons/caret.tsx
  libs/hpc-ui/src/lib/classes.ts
  tools/remove-unneeded-deps.js
Labels: ready for review

#355 Update develop with changes from env/stage
  package-lock.json
  package.json
Labels: mergeback

#356 🚀 Release `v1.4.0` and deploy to production
  apps/hpc-cdm/src/app/components/enketo/index.tsx
  apps/hpc-cdm/src/app/components/form-assignments-list.tsx
  apps/hpc-cdm/src/app/pages/not-logged-in.tsx
  apps/hpc-cdm/src/environments/interface.ts
  apps/hpc-cdm/src/i18n/index.ts
  apps/hpc-cdm/src/i18n/langs/en.json
  apps/hpc-cdm/src/i18n/langs/es.json
  apps/hpc-cdm/src/i18n/langs/es.ts
  apps/hpc-cdm/src/i18n/langs/fr.json
  apps/hpc-cdm/src/libraries/dayjs.ts
  libs/hpc-core/src/lib/i18n/index.ts
  libs/hpc-core/src/lib/session.ts
  libs/hpc-core/src/lib/util/index.ts
  libs/hpc-live/src/lib/live.ts
  libs/hpc-live/src/lib/model.ts
  libs/hpc-ui/src/lib/assets/icons/caret.tsx
  libs/hpc-ui/src/lib/classes.ts
  package-lock.json
  package.json
  tools/remove-unneeded-deps.js
Labels: deployment

#359 🌐 Minor update to Spanish translation
  apps/hpc-cdm/src/i18n/langs/es.json
Labels: ready for review

#360 📦️ Prepare release `v1.4.1` and deploy to stage
  apps/hpc-cdm/src/i18n/langs/es.json
  package-lock.json
  package.json
Labels: deployment

#362 🚀 Release `v1.4.1` and deploy to production
  apps/hpc-cdm/src/i18n/langs/es.json
  package-lock.json
  package.json
Labels: deployment
