Repository UN-OCHA/hpc-cdm, pull requests merged in 2024-06, with the labels that each got.

#448 Add new custom codecs
  libs/hpc-data/src/lib/util.ts
Labels: ready for merge

#445 HPC-8676: Start using GitHub Action that supports monorepo
  .github/ci.sh
  .github/workflow.config.json
  .github/workflows/workflow.yml
  Dockerfile
Labels: ready for merge

#451 📦️ Prepare release v1.9.0 and deploy to stage
  .github/ci.sh
  .github/workflow.config.json
  .github/workflows/workflow.yml
  Dockerfile
  libs/hpc-data/src/lib/util.ts
  package-lock.json
  package.json
Labels: deployment

#452 Update develop with changes from env/stage
  package-lock.json
  package.json
Labels: mergeback

#453 🚀 Release `v1.9.0` and deploy to production
  .github/ci.sh
  .github/workflow.config.json
  .github/workflows/workflow.yml
  Dockerfile
  libs/hpc-data/src/lib/util.ts
  package-lock.json
  package.json
Labels: deployment
