Repository UN-OCHA/hpc-cdm, pull requests merged in 2024-01, with the labels that each got.

#422 📦️ Prepare release `v1.7.3` and deploy to stage
  package-lock.json
  package.json
Labels: deployment

#423 Update develop with changes from env/stage
  package-lock.json
  package.json
Labels: mergeback

#425 🚀 Release `v1.7.3` and deploy to production
  package-lock.json
  package.json
Labels: deployment

#424 Update CodeQL Action to v3
  .github/workflows/codeql-analysis.yml
Labels: ready for merge
