Repository UN-OCHA/hpc-cdm, pull requests merged in 2025-08, with the labels that each got.

#542 HPC-10265 FTS Admin improvements post deployment
  apps/hpc-ftsadmin/src/app/components/flow-form/flow-form.tsx
  apps/hpc-ftsadmin/src/app/components/flow-form/inputs/review-pending-values.tsx
  apps/hpc-ftsadmin/src/app/utils/codecs.ts
  apps/hpc-ftsadmin/src/app/utils/parse-flow-form.ts
  apps/hpc-ftsadmin/src/app/utils/useQueryParams.tsx
Labels: ready for review

#554 HPC-10279 - Remove unsafe array access from report-detail
  apps/hpc-ftsadmin/src/app/components/reporting-detail.tsx
  apps/hpc-ftsadmin/src/app/error.tsx
  apps/hpc-ftsadmin/src/app/pages/flows/flow-error-boundary.tsx
  apps/hpc-ftsadmin/src/i18n/langs/ar.json
  apps/hpc-ftsadmin/src/i18n/langs/en.json
  apps/hpc-ftsadmin/src/i18n/langs/es.json
  apps/hpc-ftsadmin/src/i18n/langs/fr.json
  apps/hpc-ftsadmin/src/i18n/langs/zh.json
  apps/hpc-ftsadmin/src/main.tsx
Labels: ready for review

#555 HPC-10276 - Add better visualization for XLSX/XLS upload errors
  apps/hpc-ftsadmin/src/app/components/xlsx-error-display.tsx
  apps/hpc-ftsadmin/src/app/components/xlsx-uploader.tsx
  apps/hpc-ftsadmin/src/i18n/langs/ar.json
  apps/hpc-ftsadmin/src/i18n/langs/en.json
  apps/hpc-ftsadmin/src/i18n/langs/es.json
  apps/hpc-ftsadmin/src/i18n/langs/fr.json
  apps/hpc-ftsadmin/src/i18n/langs/zh.json
  libs/hpc-ui/src/lib/components/form-fields/upload-file-field.tsx
Labels: ready for merge

#559 📦 Prepare release `v1.15.0` and deploy to stage
  .env.example.json
  apps/hpc-ftsadmin/src/app/components/reporting-detail.tsx
  apps/hpc-ftsadmin/src/app/components/xlsx-error-display.tsx
  apps/hpc-ftsadmin/src/app/components/xlsx-uploader.tsx
  apps/hpc-ftsadmin/src/app/error.tsx
  apps/hpc-ftsadmin/src/app/pages/flows/flow-error-boundary.tsx
  apps/hpc-ftsadmin/src/environments/config-loader.ts
  apps/hpc-ftsadmin/src/environments/interface.ts
  apps/hpc-ftsadmin/src/i18n/langs/ar.json
  apps/hpc-ftsadmin/src/i18n/langs/en.json
  apps/hpc-ftsadmin/src/i18n/langs/es.json
  apps/hpc-ftsadmin/src/i18n/langs/fr.json
  apps/hpc-ftsadmin/src/i18n/langs/zh.json
  apps/hpc-ftsadmin/src/main.tsx
  libs/hpc-core/src/lib/config/index.ts
  libs/hpc-live/src/lib/model.ts
  libs/hpc-ui/src/lib/components/form-fields/upload-file-field.tsx
  package-lock.json
  package.json
Labels: deployment

#560 Update develop with changes from env/stage
  package-lock.json
  package.json
Labels: mergeback

#576 Fix production build relative path bug
  apps/hpc-cdm/src/assets/styles/enketo.css
Labels: ready for review
