Repository UN-OCHA/hpc-cdm, pull requests merged in 2025-04, with the labels that each got.

#497 📦 Prepare release `v1.10.1` and deploy to stage
  .github/workflows/stage-release.yml
  package-lock.json
  package.json
Labels: deployment

#499 🚀 Release `v1.10.1` and deploy to production
  .github/workflows/stage-release.yml
  package-lock.json
  package.json
Labels: deployment

#489 Update Projects Module domain
  .env.example.json
Labels: ready for review

#488 Upgrade nx
  .eslintrc.json
  .gitignore
  .prettierignore
  apps/hpc-cdm/project.json
  apps/hpc-ftsadmin/project.json
  package-lock.json
  package.json
Labels: ready for merge

#506 Update env/stage with changes from env/prod
  apps/hpc-cdm/src/i18n/langs/en.json
  apps/hpc-cdm/src/i18n/langs/es.json
  apps/hpc-cdm/src/i18n/langs/fr.json
  apps/hpc-cdm/src/index.html
  package-lock.json
  package.json
Labels: mergeback

#507 Update develop with changes from env/stage
  apps/hpc-cdm/src/i18n/langs/en.json
  apps/hpc-cdm/src/i18n/langs/es.json
  apps/hpc-cdm/src/i18n/langs/fr.json
  apps/hpc-cdm/src/index.html
  package-lock.json
  package.json
Labels: mergeback

#509 Update develop with changes from env/stage
  package-lock.json
  package.json
Labels: mergeback

#510 🚀 Release `v1.11.0` and deploy to production
  .env.example.json
  .eslintrc.json
  .gitignore
  .prettierignore
  apps/hpc-cdm/project.json
  apps/hpc-ftsadmin/project.json
  package-lock.json
  package.json
Labels: deployment
