Repository UN-OCHA/hpc-cdm, pull requests merged in 2025-05, with the labels that each got.

#503 HPC-9905: Upgrade to Node.js v22
  .github/workflows/codeql-analysis.yml
  .github/workflows/workflow.yml
  Dockerfile
  package-lock.json
  package.json
Labels: ready for merge

#513 📦 Prepare release `v1.12.0` and deploy to stage
  .github/workflows/codeql-analysis.yml
  .github/workflows/workflow.yml
  Dockerfile
  package-lock.json
  package.json
Labels: deployment

#515 🚀 Release `v1.12.0` and deploy to production
  .github/workflows/codeql-analysis.yml
  .github/workflows/workflow.yml
  Dockerfile
  package-lock.json
  package.json
Labels: deployment

#518 HPC-10213: Remove usage of legacy Dockerfile ENV syntax
  Dockerfile
Labels: ready for merge

#519 📦 Prepare release `v1.12.1` and deploy to stage
  Dockerfile
  package-lock.json
  package.json
Labels: deployment

#520 Update develop with changes from env/stage
  package-lock.json
  package.json
Labels: mergeback

#521 🚀 Release `v1.12.1` and deploy to production
  Dockerfile
  package-lock.json
  package.json
Labels: deployment
